version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "3003:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-network
  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app-network
  redis-app:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - .docker/redisdata:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge