version: "3.3"

services:
  app:
    build:
      args:
        user: mila
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: api-laravel
    ports:
      - "8000:8000"
    container_name: api-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    container_name: nginx-app
    networks:
      - app-network  
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d            
  mysql-app:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql-app
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  redis-app:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    container_name: redis-app
    volumes:
      - .docker/redisdata:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge